[mainConfig]
appName = "agriculture-service"
host = "0.0.0.0"
port = 8080

[postgreConfig]
host = "47.94.106.89"
port = 5432
user = "postgres"
password = "123456"
db = "friday"

[staticSrcConfig]
staticAvatarPath = "/opt/agriculture_go/static/avatars"
staticFilePath = "/opt/agriculture_go/static/file"

[jwtConfig]
jwtSecret = "bjtu"
jwtExpireTime = 36000